# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michal's blog
email: mxk7721@rit.edu
description: > # this means to ignore newlines until "baseurl:"
  Things that interest me or I'm trying to understand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mxk7721.github.io" # the base hostname & protocol for your site
#twitter_username: MichalKucer
github_username:  mxk7721

# Build settings
markdown: kramdown
